version: '3.4'
services:
  db_development:
    build:
      context: .
      dockerfile: DOCKERFILE.db.development
    image: db_development
    ports:
      - 5439:5432
    environment:
      - POSTGRES_PASSWORD=sit-down-c0mic
  api_development:
    build:
      context: .
      dockerfile: DOCKERFILE.api.development
    image: api
    command: ./bin/development-docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_development
    environment:
      - PROJECT_NAME
      - DEBUG=True
      - POSTGRES_USER=dbsuper
      - POSTGRES_NAME=dead_songs
      - POSTGRES_HOST=db_development
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=sit-down-c0mic
      - DJANGO_SECRET_KEY=r0ck.ar0und.the.c10ck
