version: '3.4'
services:
  db_development:
    build:
      context: .
      dockerfile: DOCKERFILE.db.development
    image: db_development
    ports:
      - 5439:5432
    environment:
      - POSTGRES_PASSWORD
  api_development:
    build:
      context: .
      dockerfile: DOCKERFILE.api.development
    image: api
    command: ./bin/local-docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_development
    environment:
      - PROJECT_NAME
      - DEBUG=True
      - POSTGRES_USER={LOCAL_POSTGRES_USER}
      - POSTGRES_NAME={LOCAL_POSTGRES_NAME}
      - POSTGRES_HOST={LOCAL_POSTGRES_HOST}
      - POSTGRES_PORT={LOCAL_POSTGRES_PORT}
      - POSTGRES_PASSWORD={LOCAL_POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY={LOCAL_DJANGO_SECRET_KEY}
